### ISSUE TITLE
Publish deprecation notice

### ISSUE THREAD

**Issue by kevinburkeotto** [Bruce17/safe-compare#4]
Node.js has a `timingSafeEqual` function built in as of version 6.6.0: https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b

It seems better to a) use that function if it's available and/or b) note in the README that people don't need to load a third party library to do that anymore.

**Comment by Bruce17** [comment]
Thanks for the hint, I'll update the package soon.
