### ISSUE TITLE
Shouldn't this be using `Buffer.byteLength`?

### ISSUE THREAD

**Issue by billinghamj** [Bruce17/safe-compare#6]
(Instead of `String.prototype.length`)

It seems to me that this is likely to result in the truncation of the string if any multi-byte characters are present:

https://github.com/Bruce17/safe-compare/blob/master/index.js#L54-L57

**Comment by billinghamj** [comment]
It looks like this issue was masked by the use of the `binary` encoding (which is lossy): https://github.com/nodejs/node/pull/5504#issuecomment-190978171

This works correctly:

```js
function safeCompare(a, b) {
    var strA = String(a);
    var strB = String(b);
    
    var len = Math.max(Buffer.byteLength(strA), Buffer.byteLength(strB));
    
    var bufA = Buffer.alloc(len, strA, 'utf8');
    var bufB = Buffer.alloc(len, strB, 'utf8');
    
    return crypto.timingSafeEqual(bufA, bufB);
}
```

**Comment by Bruce17** [comment]
Thanks for the hint. I will update the package as soon as a find time for that.

**Comment by billinghamj** [comment]
Thanks. I have also opened a PR - #7
